import { useState, useCallback, useEffect, useRef } from 'react';
import { fetchImageBlob } from '../api';

const GUESS_OPTIONS = [10, 25, 50];

const MESSAGES = {
  great: "You're incredible at this — AI doesn't stand a chance against you.",
  medium: 'Solid score. But I bet you can do even better. Another round?',
  bad: "AI wins this round. Don't worry — try again and trust your instincts.",
};

export default function GamePage() {
  const [phase, setPhase] = useState('menu'); // menu | picking | playing | over
  const [totalGuesses, setTotalGuesses] = useState(0);
  const [guessCount, setGuessCount] = useState(0);
  const [score, setScore] = useState(0);
  const [images, setImages] = useState({ left: null, right: null });
  const [correctSide, setCorrectSide] = useState(null);
  const [feedback, setFeedback] = useState(null); // { side, correct }
  const loadingRef = useRef(false);

  const loadImages = useCallback(async () => {
    if (loadingRef.current) return;
    loadingRef.current = true;
    try {
      const [original, generated] = await Promise.all([
        fetchImageBlob('/images/monet/original'),
        fetchImageBlob('/images/monet/generated'),
      ]);
      if (Math.random() < 0.5) {
        setImages({ left: original, right: generated });
        setCorrectSide('left');
      } else {
        setImages({ left: generated, right: original });
        setCorrectSide('right');
      }
    } catch (err) {
      console.error('Failed to load images:', err);
    } finally {
      loadingRef.current = false;
    }
  }, []);

  const startGame = (count) => {
    setTotalGuesses(count);
    setGuessCount(0);
    setScore(0);
    setFeedback(null);
    setPhase('playing');
  };

  useEffect(() => {
    if (phase === 'playing') loadImages();
  }, [phase, loadImages]);

  const handleGuess = (side) => {
    if (feedback || phase !== 'playing') return;
    const isCorrect = side === correctSide;
    const newScore = isCorrect ? score + 1 : score;
    const newCount = guessCount + 1;

    setFeedback({ side, correct: isCorrect });
    setScore(newScore);
    setGuessCount(newCount);

    setTimeout(() => {
      setFeedback(null);
      if (newCount >= totalGuesses) {
        setPhase('over');
      } else {
        loadImages();
      }
    }, 600);
  };

  const ratio = totalGuesses > 0 ? score / totalGuesses : 0;
  const endMessage = ratio > 0.8 ? MESSAGES.great : ratio > 0.5 ? MESSAGES.medium : MESSAGES.bad;

  return (
    <div className="mx-auto flex min-h-[calc(100vh-8rem)] max-w-6xl flex-col items-center justify-center px-4 py-12">
      {/* Hero / Menu */}
      {phase === 'menu' && (
        <div className="text-center">
          <h1 className="font-display text-4xl font-bold text-white sm:text-5xl lg:text-6xl">
            Real or <span className="text-[var(--color-gold)]">AI</span>?
          </h1>
          <p className="mx-auto mt-4 max-w-lg text-lg text-gray-400">
            One painting is by Claude Monet. The other was generated by a CycleGAN.
            Can you tell which is which?
          </p>
          <div className="mt-10 flex flex-col gap-4 sm:flex-row sm:justify-center">
            <button
              onClick={() => setPhase('picking')}
              className="rounded-xl bg-[var(--color-gold)] px-8 py-3 text-lg font-semibold text-[var(--color-dark)] transition-transform hover:scale-105 active:scale-95"
            >
              Start Game
            </button>
            <button
              onClick={() => alert('One painting is a real Monet, the other is AI-generated. Click the real one!')}
              className="rounded-xl border border-white/20 px-8 py-3 text-lg font-semibold text-gray-300 transition-colors hover:border-white/40 hover:text-white"
            >
              How to Play
            </button>
          </div>
        </div>
      )}

      {/* Pick number of rounds */}
      {phase === 'picking' && (
        <div className="text-center">
          <h2 className="font-display text-2xl font-semibold text-white sm:text-3xl">
            How many rounds?
          </h2>
          <div className="mt-8 flex gap-4">
            {GUESS_OPTIONS.map((n) => (
              <button
                key={n}
                onClick={() => startGame(n)}
                className="rounded-xl bg-[var(--color-dark-card)] px-8 py-4 text-xl font-bold text-white ring-1 ring-white/10 transition-all hover:ring-[var(--color-gold)] hover:text-[var(--color-gold)]"
              >
                {n}
              </button>
            ))}
          </div>
        </div>
      )}

      {/* Playing */}
      {phase === 'playing' && (
        <div className="flex w-full flex-col items-center gap-8">
          <p className="text-sm text-gray-400">
            Round {Math.min(guessCount + 1, totalGuesses)} of {totalGuesses} — Click the real Monet
          </p>

          <div className="grid w-full max-w-4xl grid-cols-1 gap-4 sm:grid-cols-2">
            {['left', 'right'].map((side) => (
              <button
                key={side}
                onClick={() => handleGuess(side)}
                disabled={!!feedback}
                className={`group relative overflow-hidden rounded-2xl ring-4 transition-all duration-300 ${
                  feedback?.side === side
                    ? feedback.correct
                      ? 'ring-green-500 scale-[1.02]'
                      : 'ring-red-500 scale-[0.98]'
                    : 'ring-transparent hover:ring-[var(--color-gold)]/50'
                }`}
              >
                {images[side] ? (
                  <img
                    src={images[side]}
                    alt={`Painting ${side}`}
                    className="aspect-[4/3] w-full object-cover transition-transform group-hover:scale-[1.03]"
                  />
                ) : (
                  <div className="flex aspect-[4/3] w-full items-center justify-center bg-[var(--color-dark-card)]">
                    <span className="animate-pulse text-gray-500">Loading…</span>
                  </div>
                )}
                {feedback?.side === side && (
                  <div className="absolute inset-0 flex items-center justify-center bg-black/40 text-4xl">
                    {feedback.correct ? '✓' : '✗'}
                  </div>
                )}
              </button>
            ))}
          </div>

          {/* Score bar */}
          <div className="w-full max-w-4xl">
            <div className="flex items-center justify-between text-xs text-gray-400">
              <span>Score</span>
              <span>{score} / {totalGuesses}</span>
            </div>
            <div className="mt-1 h-2 w-full overflow-hidden rounded-full bg-white/10">
              <div
                className="h-full rounded-full transition-all duration-700"
                style={{
                  width: `${(guessCount / totalGuesses) * 100}%`,
                  backgroundColor:
                    guessCount === 0
                      ? 'transparent'
                      : score / guessCount > 0.5
                        ? '#22c55e'
                        : score / guessCount > 0.25
                          ? '#f59e0b'
                          : '#ef4444',
                }}
              />
            </div>
          </div>
        </div>
      )}

      {/* Game Over */}
      {phase === 'over' && (
        <div className="text-center">
          <h2 className="font-display text-3xl font-bold text-white sm:text-4xl">Game Over</h2>
          <p className="mt-2 text-6xl font-bold text-[var(--color-gold)]">
            {score}/{totalGuesses}
          </p>
          <p className="mx-auto mt-4 max-w-md text-lg text-gray-400">{endMessage}</p>
          <button
            onClick={() => setPhase('menu')}
            className="mt-8 rounded-xl bg-[var(--color-gold)] px-8 py-3 text-lg font-semibold text-[var(--color-dark)] transition-transform hover:scale-105 active:scale-95"
          >
            Play Again
          </button>
        </div>
      )}
    </div>
  );
}
